"""Add lyrics and summary columns to Song table

Revision ID: 0304f5e561c2
Revises: 
Create Date: 2025-08-20 11:46:47.365116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0304f5e561c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('lyrics', sa.Text(), nullable=True))
    op.add_column('songs', sa.Column('lyric_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'lyric_summary')
    op.drop_column('songs', 'lyrics')
    # ### end Alembic commands ###
